name: Test

on: 
  workflow_run:
    workflows: ["Train"]
    types:
      - completed


jobs:
  test:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
